### ISSUE TITLE
Why did you removed ScrollView bounces at start and end of scrollable content?

### ISSUE THREAD

**Issue by bidah** [calebnance/expo-netflix#1]
Hey!

I was testing the app and felt this was missing but found out in your notes that you remove it on purpose. Was curious as to why because the netflix app does have it enabled.

**Comment by calebnance** [comment]
hey @bidah good eye! 👍this has been updated.
https://github.com/calebnance/expo-netflix/commit/e5931c66d7fec1958b9d121222d38a31039f1e87
