### ISSUE TITLE
Web version doesn't work.

### ISSUE THREAD

**Issue by devohno** [calebnance/expo-netflix#11]
Hi. I tried `expo start --web` for running your app with Web.
But It showed just black background.

Like this.
![Screen Shot 2019-10-25 at 1 55 59 PM](https://user-images.githubusercontent.com/55861805/67544189-6f0a9980-f72f-11e9-8863-dcb9649dbdf7.png)

**Comment by calebnance** [comment]
hi @devohno good catch, for some reason there was an issue with the override of index.html (found in web/index.html) so i renamed it for now, but all is working fine!

i created that override because at the time (super early react-native-web alpha) it wasn't displaying things correctly.
